language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r test-requirements.txt
  - pip install tox-travis
# command to run tests
script:
  - tox
  - coverage run --source amp_tools -m unittest
  - coverage report
  - codecov
