language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install tox-travis
# command to run tests
script:
  - tox
  - coverage run --source amp_tools unittest
  - coverage report
  - codecov
